### PR TITLE
Migrate pbr

### PR DESCRIPTION
**Pull request by hguemar**

### CODE REVIEW

**Comment by hguemar** [comment]
First two commits are in PR#1 and should be merged first.

**Comment by yazug** [comment]
looks like pipenv install --dev fails

**Comment by hguemar** [comment]
Nope, unless we start using pbr.version :)

**Comment by jguiditta** [comment]
This patch needs rebase (patch it depends on was merged), and tests are failing.  Also, why do we want to make this change exactly?  If there is a reason, please add to commit message.  Thanks!

**Comment by jguiditta** [comment]
FYI, I just reran travis on this with the new docker image that contains git, and it still fails.

**Comment by yazug** [comment]
this is now old, let's close and re-open pull-request with updated content if still desired

**Comment by jguiditta** [comment]
Agreed, I am not convinced of the benefit yet, anyway

**Pull request closed without merging**
